"""
schemas/email_agent.py

Reason: Pydantic schemas for the incoming email processing endpoint.
Validates structured email payloads and defines the response structure
containing processing results, sent email details, and vector store chunk count.
"""

from __future__ import annotations

from typing import Any, List, Optional
from pydantic import BaseModel, EmailStr, Field


# Reason: Request model for incoming email. Accepts structured fields or raw MIME content.
class IncomingEmailRequest(BaseModel):
    """Payload representing an incoming email to be processed by the agent."""

    sender: EmailStr = Field(..., description="Email address of the sender")
    subject: str = Field(default="", description="Subject line of the incoming email")
    body: str = Field(..., description="Plain text or HTML body of the email")
    recipients: Optional[List[EmailStr]] = Field(
        default=None, description="List of recipient email addresses (defaults to assistant/user address)"
    )
    raw_email: Optional[str] = Field(
        default=None, description="Optional raw RFC 822 / MIME email string"
    )


# Reason: Response model returning complete execution audit: email sent flag,
# agent reply, and vector store chunk ingestion statistics.
class ProcessEmailResponse(BaseModel):
    """Result returned after parsing, agent reasoning, email dispatch, and vector store persistence."""

    status: str = Field(..., description="Overall status ('success', 'failed', or 'no_email_sent')")
    incoming_email_id: str = Field(..., description="ID assigned to the incoming email")
    sender: str = Field(..., description="Sender of the incoming email")
    subject: str = Field(..., description="Subject of the incoming email")
    email_sent: bool = Field(..., description="Whether a reply email was successfully dispatched")
    sent_details: Optional[dict[str, Any]] = Field(
        default=None, description="Details of the sent reply email (to, subject, message_id)"
    )
    reply_email_id: Optional[str] = Field(
        default=None, description="ID assigned to the reply email in the vector store"
    )
    chunks_stored: int = Field(
        default=0, description="Number of text chunks embedded and stored in ChromaDB"
    )
    agent_reply: str = Field(
        default="", description="Final text response / explanation generated by the agent"
    )
